config:
  send_anonymous_usage_stats: false
  partial_parse: true
university_sample:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: rosetta/university_sample.duckdb
      schema: main
      threads: 4
